---
title: 'Project 2: Course'
author: "S Santos"
date: "Sunday, October 05, 2014"
output: html_document
---

# GRADING

## Project 1 

* To be *delivered* **on the 9th of October**

You can find Project 1 [here](https://github.com/AdvancedForcesGroup/Projects1)

This project related to Force Feedback Microscopy and counts for **10% of the total grade**.

Note: The weight of this project has changed since most of you have dedicated much effort to this project already. 




## Projects 2 OR 3

* To be *delivered* on the **Last week of November or first week of December ** 

Each group will choose a Project, i.e. 2 or 3, and these will count for **40-50% of the final grade**. You need to do one of these **ONLY**.

You can find them:

* Project 2: [here](https://github.com/AdvancedForcesGroup/Projects2/blob/master/Project2.Rmd)

* Project 3: [here](https://github.com/AdvancedForcesGroup/Projects3/blob/master/Project3.Rmd)


## Project 4 

* To be *delivered* on the ** first weeks of December ** 

You can find Project 4 [here](https://github.com/AdvancedForcesGroup/Projects4/blob/master/Homework_Project4.Rmd)

This project relates to noise in AFM and accounts for **10% of the total grade**.


## OTHER GRADING

* During the course you will also:

1. Give presentations on other selected papers. 

2. Carry out experimental work with the AFM


The above will count towards the final NET grade. 

Dr Chiesa and Dr Santos will reserve the right to assign the rest of the grades to individual performance, i.e. answering questions during presentations, quality of experimental work,  etc. 



